apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.agentToken.kubernetesSecretName | quote }}
  labels:
    app.kubernetes.io/part-of: llvm-eks-mirror
spec:
  refreshInterval: {{ .Values.agentToken.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.agentToken.secretStoreName | quote }}
  target:
    name: {{ .Values.agentToken.kubernetesSecretName | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: BUILDKITE_AGENT_TOKEN
      remoteRef:
        key: {{ required "agentToken.awsSecretArn is required" .Values.agentToken.awsSecretArn | quote }}
        property: {{ .Values.agentToken.awsSecretJsonKey | quote }}
