apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.agentToken.secretStoreName | quote }}
  labels:
    app.kubernetes.io/part-of: llvm-eks-mirror
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ required "awsRegion is required" .Values.awsRegion | quote }}
