apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.mirror.storageClassName | quote }}
  labels:
    app.kubernetes.io/part-of: llvm-eks-mirror
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ required "efsFileSystemId is required" .Values.efsFileSystemId | quote }}
  directoryPerms: "0750"
  ensureUniqueDirectory: "true"
  reuseAccessPoint: "false"
reclaimPolicy: Delete
mountOptions:
  - tls
volumeBindingMode: Immediate
