awsRegion: ""
efsFileSystemId: ""

mirror:
  storageClassName: buildkite-efs
  persistentVolumeClaimName: buildkite-git-mirrors
  requestedStorage: 20Gi

agentToken:
  secretStoreName: aws-secrets-manager
  awsSecretArn: ""
  awsSecretJsonKey: BUILDKITE_AGENT_TOKEN
  kubernetesSecretName: buildkite-agent-token
  refreshInterval: 1h
